const emojiMap = {
    joy: '😂',
    smile: '😊',
    thumbsup: '👍',
    heart: '❤️',
    fire: '🔥',
    rocket: '🚀',
    eyes: '👀',
    money: '💰',
    party: '🎉',
    question: '❓',
    exclamation: '❗',
    star: '⭐',
    speech_bubble: '💬',
    camera: '📷',
    video_camera: '📹',
    clock: '🕒',
    bomb: '💣',
    beer: '🍺',
    wine: '🍷',
    cocktail: '🍹',
    hamburger: '🍔',
    pizza: '🍕',
    fries: '🍟',
    taco: '🌮',
    ice_cream: '🍨',
    cake: '🍰',
    lollipop: '🍭',
    sushi: '🍣',
    coffee: '☕',
    thumbsdown: '👎',
    broken_heart: '💔',
    eyes: '👀',
    money_with_wings: '💸',
    gem: '💎',
    clapping_hands: '👏',
    ok_hand: '👌',
    thumbsup: '👍',
    thumbsdown: '👎',
    star_struck: '🤩',
    crying_face: '😢',
    loudly_crying_face: '😭',
    weary_face: '😩',
    pleading_face: '🥺',
    angry_face: '😠',
    heart_eyes: '😍',
    kissing_face: '😘',
    smiling_face_with_sunglasses: '😎',
    nerd_face: '🤓',
    sleeping_face: '😴',
    skull: '💀',
};

window.emojiMap = emojiMap;